language: csharp
solution: source/MasterDevs.Lib.sln

install:
  - nuget restore source/MasterDevs.Lib.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release source/MasterDevs.Lib.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe source/MasterDevs.Lib.Tests/bin/Release/MasterDevs.Lib.Tests.dll

deploy:
  provider: releases
  api_key: 99f1b5c66017c00b693e1ea1a04931e6f086d664
  file: 
    - source/MasterDevs.Lib.Tests/bin/Release/MasterDevs.Lib.Tests.dll
    - source/MasterDevs.Lib.Tests/bin/Release/MasterDevs.Lib.Tests.pdb
  skip_cleanup: true
  on:
    tags: true
